use anchor_lang::prelude::*;
declare_id!("sQjSNmjaDijHTWCu1P25HYQF3QendugoS91ZBxdN34w"); //autogenerated id generated when anchor program is deployed.
#[program]
pub mod healthchain {
    use super::*;

    /// Instruction: Create a new patient account (PDA)
    pub fn create_patient(
        ctx: Context<CreatePatient>,
        name: String,
        age: u8,
        gender: String,
    ) -> Result<()> {
        let patient = &mut ctx.accounts.patient;

        // Who owns this account? → The connected wallet
        patient.authority = ctx.accounts.authority.key();

        // Save patient details
        patient.name = name;
        patient.age = age;
        patient.gender = gender;

        msg!(" Patient account created for: {}", patient.name);
        Ok(())
    }
}

/// PDA Account Structure (Like DB table schema)
#[account]
pub struct PatientAccount {
    pub authority: Pubkey, // Wallet address (owner of this patient record)
    pub name: String,      // Patient name
    pub age: u8,           // Age
    pub gender: String,    // Gender
}

/// Context: Defines which accounts this instruction can access & modify
#[derive(Accounts)]
pub struct CreatePatient<'info> {
    /// The PDA where patient data is stored
    #[account(
        init, // Creates a new account on chain
        seeds = [b"patient", authority.key().as_ref()], // Unique per wallet
        bump,
        payer = authority, // The patient pays for account creation
        space = 8   // Anchor account discriminator
              + 32  // Pubkey (authority)
              + 4 + 50 // String: name (max 50 chars, 4 bytes length prefix)
              + 1  // Age (u8)
              + 4 + 10 // String: gender (max 10 chars)
    )]
    pub patient: Account<'info, PatientAccount>,

    /// The wallet creating the account
    #[account(mut)]
    pub authority: Signer<'info>,

    /// System program (needed for account creation)
    pub system_program: Program<'info, System>,
}